feature/add nominatim service
DUT-Info-Montreuil/SAE-5.A-carmate pull request #48
Opened 2023-12-30 03:38 UTC by LiberiBg

2023-12-30 16:21 UTC, almerion requested changes

2023-12-30 16:21 UTC, almerion commented on docker-compose.develop.yml
> +        NOMINATIM_PASSWORD: tompere
Je suis pas trop sur du password là ptdrrrrrr

2023-12-30 16:57 UTC, LiberiBg commented on docker-compose.develop.yml
> +        NOMINATIM_PASSWORD: tompere
j'vois aucun problème chef

2023-12-30 17:38 UTC, almerion approved these changes
LGTM 🚀

2023-12-30 18:36 UTC, naulan-chrzaszcz requested changes
Mot de passe non approprié pour fournir le produit fini au client via ce repo
Le Postgres Tuning a des valeurs mise a un aléatoirement si ce n'est pas le cas, le commenté car tu met 2Gb a WORK_MEM mais pourquoi ?
Pour `shm-size` il y a pas moyen de le set a 1Gb ?

2023-12-30 18:36 UTC, naulan-chrzaszcz commented on docker-compose.develop.yml
> +        POSTGRES_SHARED_BUFFERS: 2GB
```suggestion
        # PostgreSQL Tuning
        POSTGRES_SHARED_BUFFERS: 2GB
```

2023-12-30 18:36 UTC, naulan-chrzaszcz commented on docker-compose.develop.yml
> +        POSTGRES_EFFECTIVE_CACHE_SIZE: 2GB
Pourquoi avoir reattribuer les valeurs par les valeurs par default ?

2023-12-30 18:37 UTC, naulan-chrzaszcz commented
Revoir le titre de la PR

2023-12-30 18:52 UTC, LiberiBg commented on docker-compose.develop.yml
> +        POSTGRES_EFFECTIVE_CACHE_SIZE: 2GB
J'vais tester, à la base j'avais du limiter les valeurs pour le VPS, puis j'ai re-augmenter pour la prod

2023-12-30 22:39 UTC, naulan-chrzaszcz requested changes

2023-12-30 22:39 UTC, naulan-chrzaszcz commented on docker-compose.develop.yml
> +      - "8181:8080"
```suggestion
      - 8181:8080
```

2023-12-30 22:39 UTC, naulan-chrzaszcz commented on docker-compose.develop.yml
> +        - nominatim-data:/var/lib/postgresql/14/main
```suggestion
        - ./nominatim-data:/var/lib/postgresql/14/main
```

2023-12-30 22:39 UTC, naulan-chrzaszcz commented on docker-compose.develop.yml
> +    nominatim-data:
J'me demande si c'est vraiment obligatoire, essaye de l'enlever

2023-12-30 22:39 UTC, naulan-chrzaszcz commented on docker-compose.develop.yml
> +        NOMINATIM_PASSWORD: nominatimpsswd
```suggestion
    environment:
        - PBF_URL=https://download.geofabrik.de/europe/france/ile-de-france-latest.osm.pbf 
        - REPLICATION_URL=https://download.geofabrik.de/europe/france-updates/
        - NOMINATIM_PASSWORD=nominatimpsswd
```

2023-12-30 22:39 UTC, naulan-chrzaszcz commented on docker-compose.develop.yml
> +  nominatim:
Le front dépend de l'API nominatim, ajoute au container `front` un `depends_on` de `nominatim`

2023-12-30 22:39 UTC, naulan-chrzaszcz commented on docker-compose.develop.yml
> +        - nominatim-data:/var/lib/postgresql/14/main
Si c'est un directory

2023-12-30 22:39 UTC, naulan-chrzaszcz commented on docker-compose.develop.yml
> +    nominatim-data:
(si c'est un directory)

2023-12-30 22:39 UTC, naulan-chrzaszcz commented on docker-compose.develop.yml
> +  nominatim:
Et regarde si tu peux ajouter un `healthcheck` a nominatim

2024-01-04 23:26 UTC, LiberiBg commented on docker-compose.develop.yml
> +        NOMINATIM_PASSWORD: nominatimpsswd
Cette syntaxe me donne envie de crever sache le

2024-01-05 00:11 UTC, naulan-chrzaszcz commented on docker-compose.develop.yml
> +        NOMINATIM_PASSWORD: nominatimpsswd
Faut avoir le même code style

2024-01-05 11:42 UTC, naulan-chrzaszcz approved these changes
LGTM !!!!!!!! 🚀🚀🚀🚀🚀🚀🚀

2024-01-06 22:28 UTC, merged